name: Node.js CI
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: cd TP_DOCKER_3 && docker build -t tp-docker-3 .

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.JS 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: cd TP_DOCKER_3 && npm run lint
